# --- Sample dataset

# --- !Ups

insert into usuario (nome, email, senha, privilegio, status, validado) values ('Administrador', 'admin', '40BD001563085FC35165329EA1FF5C5ECBDBBEEF', 1, TRUE, TRUE);

insert into escolaridade (nome) values ('Ensino Médio Completo');
insert into escolaridade (nome) values ('Ensino Técnico');
insert into escolaridade (nome) values ('Graduação (Bacharelado)');
insert into escolaridade (nome) values ('Graduação (Licenciatura)');
insert into escolaridade (nome) values ('Especialização (Lato Sensu)');
insert into escolaridade (nome) values ('Mestrado (Stricto Sensu)');
insert into escolaridade (nome) values ('Doutorado (Stricto Sensu)');

insert into genero (nome) values ('Masculino');
insert into genero (nome) values ('Feminino');

insert into modalidade (nome) values ('Sim');
insert into modalidade (nome) values ('Não');

insert into fonte (nome) values ('Site do CIBiogás-ER');
insert into fonte (nome) values ('Indicação de amigos');
insert into fonte (nome) values ('Facebook');
insert into fonte (nome) values ('Email');
insert into fonte (nome) values ('Outro');

insert into pais (nome) values ('Afghanistan');
insert into pais (nome) values ('Albania');
insert into pais (nome) values ('Algeria');
insert into pais (nome) values ('Andorra');
insert into pais (nome) values ('Angola');
insert into pais (nome) values ('Anguilla');
insert into pais (nome) values ('Antarctica');
insert into pais (nome) values ('Antigua and Barbuda');
insert into pais (nome) values ('Argentina');
insert into pais (nome) values ('Armenia');
insert into pais (nome) values ('Aruba');
insert into pais (nome) values ('Australia');
insert into pais (nome) values ('Austria');
insert into pais (nome) values ('Azerbaijan');
insert into pais (nome) values ('Bahamas');
insert into pais (nome) values ('Bahrain');
insert into pais (nome) values ('Bangladesh');
insert into pais (nome) values ('Barbados');
insert into pais (nome) values ('Belarus');
insert into pais (nome) values ('Belgium');
insert into pais (nome) values ('Belize');
insert into pais (nome) values ('Benin');
insert into pais (nome) values ('Bermuda');
insert into pais (nome) values ('Bhutan');
insert into pais (nome) values ('Bolivia');
insert into pais (nome) values ('Plurinational State of');
insert into pais (nome) values ('Bosnia and Herzegovina');
insert into pais (nome) values ('Botswana');
insert into pais (nome) values ('Bouvet Island');
insert into pais (nome) values ('Brazil');
insert into pais (nome) values ('British Indian Ocean Territory');
insert into pais (nome) values ('Brunei Darussalam');
insert into pais (nome) values ('Bulgaria');
insert into pais (nome) values ('Burkina Faso');
insert into pais (nome) values ('Burundi');
insert into pais (nome) values ('Cambodia');
insert into pais (nome) values ('Cameroon');
insert into pais (nome) values ('Canada');
insert into pais (nome) values ('Cape Verde');
insert into pais (nome) values ('Cayman Islands');
insert into pais (nome) values ('Central African Republic');
insert into pais (nome) values ('Chad');
insert into pais (nome) values ('Chile');
insert into pais (nome) values ('China');
insert into pais (nome) values ('Christmas Island');
insert into pais (nome) values ('Cocos (Keeling) Islands');
insert into pais (nome) values ('Colombia');
insert into pais (nome) values ('Comoros');
insert into pais (nome) values ('Congo');
insert into pais (nome) values ('Congo the Democratic Republic of the');
insert into pais (nome) values ('Cook Islands');
insert into pais (nome) values ('Costa Rica');
insert into pais (nome) values ('Croatia');
insert into pais (nome) values ('Cuba');
insert into pais (nome) values ('Cyprus');
insert into pais (nome) values ('Czech Republic');
insert into pais (nome) values ('Denmark');
insert into pais (nome) values ('Djibouti');
insert into pais (nome) values ('Dominica');
insert into pais (nome) values ('Dominican Republic');
insert into pais (nome) values ('Ecuador');
insert into pais (nome) values ('Egypt');
insert into pais (nome) values ('El Salvador');
insert into pais (nome) values ('Equatorial Guinea');
insert into pais (nome) values ('Eritrea');
insert into pais (nome) values ('Estonia');
insert into pais (nome) values ('Ethiopia');
insert into pais (nome) values ('Falkland Islands (Malvinas)');
insert into pais (nome) values ('Faroe Islands');
insert into pais (nome) values ('Fiji');
insert into pais (nome) values ('Finland');
insert into pais (nome) values ('France');
insert into pais (nome) values ('French Guiana');
insert into pais (nome) values ('French Polynesia');
insert into pais (nome) values ('French Southern Territories');
insert into pais (nome) values ('Gabon');
insert into pais (nome) values ('Gambia');
insert into pais (nome) values ('Georgia');
insert into pais (nome) values ('Germany');
insert into pais (nome) values ('Ghana');
insert into pais (nome) values ('Gibraltar');
insert into pais (nome) values ('Greece');
insert into pais (nome) values ('Greenland');
insert into pais (nome) values ('Grenada');
insert into pais (nome) values ('Guadeloupe');
insert into pais (nome) values ('Guam');
insert into pais (nome) values ('Guatemala');
insert into pais (nome) values ('Guernsey');
insert into pais (nome) values ('Guinea');
insert into pais (nome) values ('Guinea-Bissau');
insert into pais (nome) values ('Guyana');
insert into pais (nome) values ('Haiti');
insert into pais (nome) values ('Heard Island and McDonald Islands');
insert into pais (nome) values ('Holy See (Vatican City State)');
insert into pais (nome) values ('Honduras');
insert into pais (nome) values ('Hong Kong');
insert into pais (nome) values ('Hungary');
insert into pais (nome) values ('Iceland');
insert into pais (nome) values ('India');
insert into pais (nome) values ('Indonesia');
insert into pais (nome) values ('Iran Islamic Republic of');
insert into pais (nome) values ('Iraq');
insert into pais (nome) values ('Ireland');
insert into pais (nome) values ('Isle of Man');
insert into pais (nome) values ('Israel');
insert into pais (nome) values ('Italy');
insert into pais (nome) values ('Jamaica');
insert into pais (nome) values ('Japan');
insert into pais (nome) values ('Jersey');
insert into pais (nome) values ('Jordan');
insert into pais (nome) values ('Kazakhstan');
insert into pais (nome) values ('Kenya');
insert into pais (nome) values ('Kiribati');
insert into pais (nome) values ('Korea Democratic Peoples Republic of');
insert into pais (nome) values ('Korea Republic of');
insert into pais (nome) values ('Kuwait');
insert into pais (nome) values ('Kyrgyzstan');
insert into pais (nome) values ('Lao Peoples Democratic Republic');
insert into pais (nome) values ('Latvia');
insert into pais (nome) values ('Lebanon');
insert into pais (nome) values ('Lesotho');
insert into pais (nome) values ('Liberia');
insert into pais (nome) values ('Libyan Arab Jamahiriya');
insert into pais (nome) values ('Liechtenstein');
insert into pais (nome) values ('Lithuania');
insert into pais (nome) values ('Luxembourg');
insert into pais (nome) values ('Macao');
insert into pais (nome) values ('Macedonia the former Yugoslav Republic of');
insert into pais (nome) values ('Madagascar');
insert into pais (nome) values ('Malawi');
insert into pais (nome) values ('Malaysia');
insert into pais (nome) values ('Maldives');
insert into pais (nome) values ('Mali');
insert into pais (nome) values ('Malta');
insert into pais (nome) values ('Marshall Islands');
insert into pais (nome) values ('Martinique');
insert into pais (nome) values ('Mauritania');
insert into pais (nome) values ('Mauritius');
insert into pais (nome) values ('Mayotte');
insert into pais (nome) values ('Mexico');
insert into pais (nome) values ('Micronesia Federated States of');
insert into pais (nome) values ('Moldova Republic of');
insert into pais (nome) values ('Monaco');
insert into pais (nome) values ('Mongolia');
insert into pais (nome) values ('Montenegro');
insert into pais (nome) values ('Montserrat');
insert into pais (nome) values ('Morocco');
insert into pais (nome) values ('Mozambique');
insert into pais (nome) values ('Myanmar');
insert into pais (nome) values ('Namibia');
insert into pais (nome) values ('Nauru');
insert into pais (nome) values ('Nepal');
insert into pais (nome) values ('Netherlands');
insert into pais (nome) values ('Netherlands Antilles');
insert into pais (nome) values ('New Caledonia');
insert into pais (nome) values ('New Zealand');
insert into pais (nome) values ('Nicaragua');
insert into pais (nome) values ('Niger');
insert into pais (nome) values ('Nigeria');
insert into pais (nome) values ('Niue');
insert into pais (nome) values ('Norfolk Island');
insert into pais (nome) values ('Northern Mariana Islands');
insert into pais (nome) values ('Norway');
insert into pais (nome) values ('Oman');
insert into pais (nome) values ('Pakistan');
insert into pais (nome) values ('Palau');
insert into pais (nome) values ('Palestinian Territory Occupied');
insert into pais (nome) values ('Panama');
insert into pais (nome) values ('Papua New Guinea');
insert into pais (nome) values ('Paraguay');
insert into pais (nome) values ('Peru');
insert into pais (nome) values ('Philippines');
insert into pais (nome) values ('Pitcairn');
insert into pais (nome) values ('Poland');
insert into pais (nome) values ('Portugal');
insert into pais (nome) values ('Puerto Rico');
insert into pais (nome) values ('Qatar');
insert into pais (nome) values ('Romania');
insert into pais (nome) values ('Russian Federation');
insert into pais (nome) values ('Rwanda');
insert into pais (nome) values ('Saint Helena Ascension and Tristan da Cunha');
insert into pais (nome) values ('Saint Kitts and Nevis');
insert into pais (nome) values ('Saint Lucia');
insert into pais (nome) values ('Saint Martin (French part)');
insert into pais (nome) values ('Saint Pierre and Miquelon');
insert into pais (nome) values ('Saint Vincent and the Grenadines');
insert into pais (nome) values ('Samoa');
insert into pais (nome) values ('San Marino');
insert into pais (nome) values ('Sao Tome and Principe');
insert into pais (nome) values ('Saudi Arabia');
insert into pais (nome) values ('Senegal');
insert into pais (nome) values ('Serbia');
insert into pais (nome) values ('Seychelles');
insert into pais (nome) values ('Sierra Leone');
insert into pais (nome) values ('Singapore');
insert into pais (nome) values ('Slovakia');
insert into pais (nome) values ('Slovenia');
insert into pais (nome) values ('Solomon Islands');
insert into pais (nome) values ('Somalia');
insert into pais (nome) values ('South Africa');
insert into pais (nome) values ('South Georgia and the South Sandwich Islands');
insert into pais (nome) values ('Spain');
insert into pais (nome) values ('Sri Lanka');
insert into pais (nome) values ('Sudan');
insert into pais (nome) values ('Suriname');
insert into pais (nome) values ('Svalbard and Jan Mayen');
insert into pais (nome) values ('Swaziland');
insert into pais (nome) values ('Sweden');
insert into pais (nome) values ('Switzerland');
insert into pais (nome) values ('Syrian Arab Republic');
insert into pais (nome) values ('Taiwan Province of China');
insert into pais (nome) values ('Tajikistan');
insert into pais (nome) values ('Tanzania United Republic of');
insert into pais (nome) values ('Thailand');
insert into pais (nome) values ('Timor-Leste');
insert into pais (nome) values ('Togo');
insert into pais (nome) values ('Tokelau');
insert into pais (nome) values ('Tonga');
insert into pais (nome) values ('Trinidad and Tobago');
insert into pais (nome) values ('Tunisia');
insert into pais (nome) values ('Turkey');
insert into pais (nome) values ('Turkmenistan');
insert into pais (nome) values ('Turks and Caicos Islands');
insert into pais (nome) values ('Tuvalu');
insert into pais (nome) values ('Uganda');
insert into pais (nome) values ('Ukraine');
insert into pais (nome) values ('United Arab Emirates');
insert into pais (nome) values ('United Kingdom');
insert into pais (nome) values ('United States');
insert into pais (nome) values ('United States Minor Outlying Islands');
insert into pais (nome) values ('Uruguay');
insert into pais (nome) values ('Uzbekistan');
insert into pais (nome) values ('Vanuatu');
insert into pais (nome) values ('Venezuela Bolivarian Republic of');
insert into pais (nome) values ('Viet Nam');
insert into pais (nome) values ('Virgin Islands British');
insert into pais (nome) values ('Virgin Islands U.S.');
insert into pais (nome) values ('Wallis and Futuna');
insert into pais (nome) values ('Western Sahara');
insert into pais (nome) values ('Yemen');
insert into pais (nome) values ('Zambia');
insert into pais (nome) values ('Zimbabwe');



